# networks:
#   ros:
#     driver: bridge

services:

  main:
    image: jetson
    build: .  
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    environment: 
     - DISPLAY=$DISPLAY
    stdin_open: true
    tty: true
    restart: always

