twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyboard_teleop:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 100